services:
  app:
    build: .
    container_name: nest-todo-app
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/NEST-TODO-APP
      - /NEST-TODO-APP/node_modules
    command: npm run start:dev
